config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  before_filter :authenticate_for_admin, :only => [:new_teacher, :save_teacher, :edit_teacher]
  before_filter :authenticate
  
  def index
    redirect_to teacher_timesheet_path(session[:user_id])
  end

  def new_teacher
    session[:nr_of_courses] = DEFAULT_NR_OF_COURSES
    @nr_of_courses = session[:nr_of_courses]
    @course_types = CourseType.all 
  end

  def save_teacher
    @nr_of_courses = session[:nr_of_courses]
    @course_types = CourseType.all

    unless params[:add_course].nil?
      @nr_of_courses += 1
      session[:nr_of_courses] = @nr_of_courses

      flash.now[:params] = params

      render "new_teacher"
    else
      session[:edited_user_id] = nil
      @edited_user_id = session[:edited_user_id]

      if save_teacher_to_db "new_teacher"
        session[:nr_of_courses] = nil
   
        redirect_to admin_path
      end
    end
  end
  
  def edit_teacher
    @teachers = User.where( :role_id => Role.where( :permission => "teacher").first.id )
    
    @nr_of_courses = session[:nr_of_courses]
    @course_types = CourseType.all
    @disabled = nil
    
    unless params[:id].nil?
      session[:edited_user_id] = params[:id]
      @edited_user_id = session[:edited_user_id]
    end
    
    if params[:add_course] != nil
      @nr_of_courses += 1
      session[:nr_of_courses] = @nr_of_courses

      @course_ids = session[:course_ids]
      @edited_user_id = session[:edited_user_id]

      flash.now[:params] = params

      render "edit_teacher"
    elsif params.has_value? t(:remove_course)
      remove_course_id = params.key t(:remove_course)

      @nr_of_courses -= 1 unless @nr_of_courses == 0
      session[:nr_of_courses] = @nr_of_courses
      
      @edited_user_id = session[:edited_user_id]
      
      unless session[:course_ids].nil?
        session[:course_ids] = session[:course_ids].find_all do |course_id|
          course_id.to_i != remove_course_id.to_i
        end
        
        @course_ids = session[:course_ids]
        
        teacher = User.where(:id => session[:edited_user_id]).first
        
        i = 0
        j = 0
        teacher.teaches.all.each do |teach|
          found = false
          session[:course_ids].each do |course_id|
            if course_id.to_i == teach.course.id.to_i
              found = true
              break
            end
          end
          
          unless found
            params.delete("course_title" + i.to_s)
            params.delete("course_description" + i.to_s)
            params.delete("course_semester" + i.to_s)
            params.delete("course_code" + i.to_s)
            
            hours = teach.hours.all
            hours.each do |hour|
              params.delete("course" + i.to_s + "_type_id_" + hour.course_type.id.to_s)
            end
          else
            params["course_title" + j.to_s] = teach.course.title
            params["course_description" + j.to_s] = teach.course.description
            params["course_semester" + j.to_s] = teach.course.semester
            params["course_code" + j.to_s] = teach.course.code
            
            hours = teach.hours.all
            hours.each do |hour|
              params["course" + j.to_s + "_type_id_" + hour.course_type.id.to_s] = hour.hours.to_i / 3600
            end
            
            j += 1
          end
          i += 1
        end
      end

      flash.now[:params] = params

      render "edit_teacher"
    elsif params[:update_teacher] != nil
      if save_teacher_to_db "edit_teacher"
        edit_user_id = session[:edited_user_id]
        session[:nr_of_courses] = nil
        session[:edited_user_id] = nil
        @edited_user_id = session[:edited_user_id]
        session[:course_ids] = nil
        
        flash.now[:error] = "Saved"
  
        redirect_to admin_edit_teacher_path(edit_user_id)
      end
    elsif params[:id].nil?
      session[:nr_of_courses] = DEFAULT_NR_OF_COURSES
      @nr_of_courses = session[:nr_of_courses]
      @disabled = "disabled"
      @course_ids = []
    else
      session[:course_ids] = nil
      
      teacher = User.where(:id => params[:id]).first
      
      if teacher.nil?
        @disabled = "disabled"
        return
      end 
      
      params[:username] = teacher.name
      params[:password] = teacher.password
      
      teaches = teacher.teaches.all
      session[:course_ids] = teacher.course_ids
      @course_ids = session[:course_ids]
      
      @nr_of_courses = teaches.length
      session[:nr_of_courses] = @nr_of_courses
      
      teaches.each_with_index do |teach, i| 
        params["course_title" + i.to_s] = teach.course.title
        params["course_description" + i.to_s] = teach.course.description
        params["course_semester" + i.to_s] = teach.course.semester
        params["course_code" + i.to_s] = teach.course.code
        
        hours = teach.hours.all
        hours.each do |hour|
          params["course" + i.to_s + "_type_id_" + hour.course_type.id.to_s] = hour.hours.to_i / 3600
        end
      end
      
      flash.now[:params] = params
      
      render "edit_teacher"
    end
  end
  
  def delete_teacher
    unless params[:id].nil?
      user = User.where(:id => params[:id]).first
      unless user.nil?
        user.destroy
      end
    end
    
    redirect_to admin_show_edit_teacher_path
  end

  private
  def save_teacher_to_db(path_to_display_error)
    if params[:username] == ""
      usernameError = "Username field empty."
    end

    if params[:password] == ""
      passwordError = "Password field empty."
    end

    courses = []
    course_types = []

    courseError = {}
    courseTypeError = {}
    session[:nr_of_courses].times do |i|
      course_fields = ["course_title", "course_code", "course_description", "course_semester"]

      course_params = {}
      course_fields.each do |course_field|
        course_tag_id = course_field + i.to_s
        if params[course_tag_id] == ""
          courseError[course_tag_id] = "Field empty."
        else
          course_params[course_field] = params[course_tag_id]
        end
      end
      
      courses << course_params

      course_type_value = []

      @course_types.each do |course_type|
        type_tag_id = "course" + i.to_s + "_type_id_" + course_type.id.to_s
        if params[type_tag_id] == ""
          courseTypeError[type_tag_id] = "Course Type field empty."
        else
          course_type_value << params[type_tag_id]
        end
      end

      course_types << course_type_value
    end

    unless usernameError.nil? && passwordError.nil? && courseError.empty? && courseTypeError.empty?
      flash.now[:passwordError] = passwordError
      flash.now[:usernameError] = usernameError
      flash.now[:courseError] = courseError
      flash.now[:courseTypeError] = courseTypeError
      flash.now[:params] = params
      render path_to_display_error
    return
    end
    
    if session[:edited_user_id] != nil
      user = User.where(:id => session[:edited_user_id]).first
    end
    
    user_courses = []
    if user.nil?
      user = User.new :name => params[:username], :password => params[:password]
      user.role = Role.where(:permission => "teacher").first
    else
      user.name = params[:username]
      user.password = params[:password]
      
      user_courses = user.courses.all
      
      unless session[:course_ids].nil?
        user_courses = user_courses.find_all do |course|
          found = false
          session[:course_ids].each do |needed_course_id|
            if needed_course_id.to_i == course.id.to_i
              found = true
              break
            end
          end
          unless found
            course.destroy
          end
          found
        end
      end
      
    end
    
    user.save
    
    course_models = []
    course_hours = []
    
    courses.each_with_index do |course_params, i|
      title = ""
      description = ""
      code = ""
      semester = ""
      
      course_params.each do |key, value|
        case key
        when "course_title"
          title = value
        when "course_code"
          code = value
        when "course_description"
          description = value
        when "course_semester"
          semester = value  
        end  
      end

      if user_courses.length < courses.length
        course = Course.where(:title => title, :code => code, :description => description, :semester => semester).first
        
        if course.nil?
          course = Course.new :title => title, :code => code, :description => description, :semester => semester
        end
      else
        course = user_courses[i]
        
        course.title = title
        course.code = code
        course.description = description
        course.semester = semester
      end
      
      course_models << course
      
      hours = []
      
      @course_types.each do |course_type|
        type_tag_id = "course" + i.to_s + "_type_id_" + course_type.id.to_s
        
        course_type_hour = params[type_tag_id]
        
        if user_courses.length < courses.length        
          hour = Hour.new :hours => Time.at(course_type_hour.to_i * 3600).gmtime
          hour.course_type = course_type
        else
          hour = user.teaches.all[i].hours.where(:course_type_id => course_type.id).first
          hour.hours = Time.at(course_type_hour.to_i * 3600).gmtime
        end
        
        hours << hour
      end
      
      course_hours << hours
    end
    
    course_models.each_with_index do |course_model, i|
      course_model.save
      
      hour_models = course_hours[i]
      
      if session[:edited_user_id] != nil &&
          user.teaches.length >= course_models.length
        teach = user.teaches.where(:user_id => session[:edited_user_id], :course_id => course_model.id).first
      else
        teach = Teach.where(:user_id => user.id, :course_id => course_model.id).first
        

app/helpers/teacher_helper.rb
module TeacherHelper
end
 

app/views/teacher/edit_teacher.html.erb
<h1 style="text-align: center;"><%= t(:edit_teacher)%></h1>
<table style="width: 100%" cellspacing="0" cellpadding="0">
	<tr>
		<td id="teachersColumn" valign="top">
			<table style="width: 100%; text-align:center;" cellspacing="0" cellpadding="0">
				<th>
					<tr style="background-color: #eee;">
						<td style="font-size: x-large; font-weight: bold;" colspan="2">
							<%= t(:teacher) %>
						</td>
					</tr>
				</th>
				<% @teachers.each do |teacher| %>
				<tr>
					<% unless @edited_user_id.nil? 
						if @edited_user_id.to_i == teacher.id.to_i %>
						<tr style="background-color: white;">
					<% 	else %>
						<tr>
					<% 	end %>
					<% else %> 
						<tr>
					<% end %>
					<td>
						<a href="<%= admin_edit_teacher_path(teacher.id)%>"><%= teacher.name%></a>
					</td>
					<td><%= link_to "x", admin_delete_teacher_path(teacher.id), :confirm => t(:confirm_teacher_delete)%></td>
				</tr>
				<% end %>
			</table>
		</td>
		<td id="editTeacherColumn" valign="top">
			<div style="background-color: #eee; font-size: x-large; font-weight: bold; text-align: center;">
				<%= t(:edit) %>
			</div>
				
			<%= form_tag admin_show_edit_teacher_path do %>
			<table style="margin-left: auto; margin-right: auto; width: 500px;">
				<tr>
					<td style="text-align: right;"><%= t(:name) %></td>
					<td colspan="2"> <%= text_field_tag :username, (flash[:params][:username] unless flash[:params].nil?), :size => 28, :disabled => @disabled %> </td>
				</tr>
				<tr>
					<td></td>
					<td class="errorCell" style="color: red;" colspan="2"> <%= flash[:usernameError]%> </td>
				</tr>
				<tr>
					<td style="text-align: right;"><%= t(:password) %></td>
					<td colspan="2"> <%= text_field_tag :password, (flash[:params][:password] unless flash[:params].nil?), :size => 28, :disabled => @disabled  %> </td>
				</tr>
				<tr>
					<td></td>
					<td class="errorCell" style="color: red;" colspan="2"> <%= flash[:passwordError]%> </td>
				</tr>
				<% @nr_of_courses.times do |i|
					course_fields = ["course_title", "course_code", "course_description", "course_semester"]
				%>
				<tr>
					<td colspan="3" style="background-color: gray;"></td>
				</tr>
				<% course_fields.each_with_index do |course_field, j|
						course_field_tag_id = course_field + i.to_s
						
						helper_tag = ""
						options_for_select = ""
						message_tag_and_size = ""
						case course_field
						when "course_description"
							helper_tag = "text_area_tag"
							message_tag_and_size = "(flash[:params][course_field_tag_id] unless flash[:params].nil?), :size => 28"
						when "course_semester"
							helper_tag = "select_tag"
							options_for_select = "options_for_select([['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8]], (flash[:params][course_field_tag_id] unless flash[:params].nil?))"
						else
							helper_tag = "text_field_tag"
							message_tag_and_size = "(flash[:params][course_field_tag_id] unless flash[:params].nil?), :size => 28"
						end
				%>
				<tr>
					<td style="text-align: right"><%= t(course_field) %></td>
					<td colspan="2"> <%= eval helper_tag + " course_field_tag_id, " + options_for_select + message_tag_and_size + ", :disabled => @disabled"  %> </td>
					<% if j == 0 %>
						<td>
							<%= submit_tag t(:remove_course), :name => ((i >= @course_ids.length) ? "-1" : @course_ids[i]), :confirm => t(:confirm_delete), :disabled => @disabled %>
						</td>
					<% end %>
				</tr>
				<tr>
					<td></td>
					<td class="errorCell" style="color: red;" colspan="2"> <%= flash[:courseError][course_field_tag_id] unless flash[:courseError].nil? %> </td>
				</tr>
					<% end %>
					<% @course_types.each do |course_type|
							tag_id = "course" + i.to_s + "_type_id_" + course_type.id.to_s
					%>
					<tr>
						<td></td>
						<td style="text-align: right;"><%= course_type.name %></td>
						<td style="text-align: left;">
							<%= select_tag tag_id, options_for_select([['0', 0], ['2', 2], ['4', 4], ['6', 6], ['8', 8], ['10', 10]], (flash[:params][tag_id] unless flash[:params].nil?)), :disabled => @disabled %> <%= t(:hours)%>/<%= t(:week)%>
						</td>
					</tr>
					<tr>
						<td></td>
						<td class="errorCell" style="color: red;" colspan="2"> 
							<%= flash[:courseTypeError][tag_id] unless flash[:courseTypeError].nil? %> 
						</td>
					</tr>
					<% end %>
				<% end %>
				<tr>
					<td></td>
					<td style="text-align: left" colspan="2"> <%= submit_tag t(:add_course), :name => :add_course, :disabled => @disabled %> </td>
				</tr>
				<tr>
					<td></td>
					<td style="text-align: right" colspan="2"> <%= submit_tag t(:save), :name => :update_teacher, :disabled => @disabled %> </td>
				</tr>
				<tr>
					<td class="errorCell" style="color: red; text-align: center;" colspan="3"> <%= flash[:error] %> </td>
				</tr>
				<tr>
					<td style="text-align: center;" colspan="3"> <%= flash[:notice] %> </td>
				</tr>
			</table>
			<% end %>
		</td>
	</tr>

app/views/teacher/index.html.erb
<h1 style="text-align: center;"><%= t(:teacher)%></h1>

<%= render :partial => "shared/time_table", :locals => {:time_table_cells => @time_table_cells} %> 

app/views/teacher/new_teacher.html.erb
<h1 style="text-align: center;"><%= t(:new_teacher)%></h1>

<%= form_tag admin_save_teacher_path do %>
<table style="margin-left: auto; margin-right: auto; width: 350px;">
	<tr>
		<td style="text-align: right;"><%= t(:name) %></td>
		<td colspan="2"> <%= text_field_tag :username, (flash[:params][:username] unless flash[:params].nil?), :size => 28 %> </td>
	</tr>
	<tr>
		<td></td>
		<td class="errorCell" style="color: red;" colspan="2"> <%= flash[:usernameError]%> </td>
	</tr>
	<tr>
		<td style="text-align: right;"><%= t(:password) %></td>
		<td colspan="2"> <%= text_field_tag :password, (flash[:params][:password] unless flash[:params].nil?), :size => 28 %> </td>
	</tr>
	<tr> 
		<td></td>
		<td class="errorCell" style="color: red;" colspan="2"> <%= flash[:passwordError]%> </td>
	</tr>
	<% @nr_of_courses.times do |i|
		course_fields = ["course_title", "course_code", "course_description", "course_semester"]
	%>
	<tr>
		<td colspan="3" style="background-color: gray;"></td>
	</tr>
	<% course_fields.each do |course_field|
			course_field_tag_id = course_field + i.to_s
			
			helper_tag = ""
			options_for_select = ""
			message_tag_and_size = ""
			case course_field
			when "course_description"
				helper_tag = "text_area_tag"
				message_tag_and_size = "(flash[:params][course_field_tag_id] unless flash[:params].nil?), :size => 28"
			when "course_semester"
				helper_tag = "select_tag"
				options_for_select = "options_for_select([['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8]], (flash[:params][course_field_tag_id] unless flash[:params].nil?))"
			else
				helper_tag = "text_field_tag"
				message_tag_and_size = "(flash[:params][course_field_tag_id] unless flash[:params].nil?), :size => 28"
			end
	%>
	<tr>
		<td style="text-align: right"><%= t(course_field) %></td>
		<td colspan="2"> <%= eval helper_tag + " course_field_tag_id, " + options_for_select + message_tag_and_size  %> </td>
	</tr>
	<tr>
		<td></td>
		<td class="errorCell" style="color: red;" colspan="2"> <%= flash[:courseError][course_field_tag_id] unless flash[:courseError].nil? %> </td>
	</tr>
		<% end %>
		<% @course_types.each do |course_type|
				tag_id = "course" + i.to_s + "_type_id_" + course_type.id.to_s
				
		%>
		<tr>
			<td></td>
			<td style="text-align: right;"><%= course_type.name %></td>
			<td style="text-align: left;">
				<%= select_tag tag_id, options_for_select([['0', 0], ['2', 2], ['4', 4], ['6', 6], ['8', 8], ['10', 10]], (flash[:params][tag_id] unless flash[:params].nil?)) %> <%= t(:hours)%>/<%= t(:week)%>
			</td>
		</tr>
		<tr>
			<td></td>
			<td class="errorCell" style="color: red;" colspan="2"> 
				<%= flash[:courseTypeError][tag_id] unless flash[:courseTypeError].nil? %> 
			</td>
		</tr>
		<% end %>
	<% end %>
	<tr>
		<td></td>
		<td style="text-align: left" colspan="2"> <%= submit_tag t(:add_course), :name => :add_course %> </td>
	</tr>
	<tr>
		<td></td>
		<td style="text-align: right" colspan="2"> <%= submit_tag t(:save) %> </td>
	</tr>
	<tr>
		<td class="errorCell" style="color: red; text-align: center;" colspan="3"> <%= flash[:error] %> </td>
	</tr>
	<tr>
		<td style="text-align: center;" colspan="3"> <%= flash[:notice] %> </td>
	</tr>
</table>
<% end %>