config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teaches, :dependent => :destroy
  has_many :users, :through => :teaches
end 

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :hours
  has_many :teaches, :through => :hours
end
 

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :teach
  belongs_to :course_type
  belongs_to :timesheet
end
 

app/models/role.rb
class Role < ActiveRecord::Base
  def admin?
    self.permission == "admin"
  end
end
 

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :user
  belongs_to :course, :dependent => :destroy
  has_many :hours, :dependent => :destroy
  has_many :wishes, :dependent => :destroy
end
 

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :hour
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # one-to-many association, the foreign key pointing to the Role table row is kept in this table
  # read for details: 
  # http://guides.rubyonrails.org/association_basics.html 
  # http://duanesbrain.blogspot.com/2006/05/ruby-on-rails-hasone-versus-belongsto.html
  belongs_to :role
  
  has_many :teaches, :dependent => :destroy
  has_many :courses, :through => :teaches
end 

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :teaches
  belongs_to :hour
end
 

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_for_admin
  
  def index
    redirect_to admin_timesheet_path
  end
  
end 

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_filter :authenticate_for_admin
  
  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hours } 
    end
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
    @hour = Hour.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/new
  # GET /hours/new.json
  def new
    @hour = Hour.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/1/edit
  def edit
    @hour = Hour.find(params[:id])
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(params[:hour])

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render json: @hour, status: :created, location: @hour }
      else
        format.html { render action: "new" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hours/1
  # PUT /hours/1.json
  def update
    @hour = Hour.find(params[:id])

    respond_to do |format|
      if @hour.update_attributes(params[:hour])
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour = Hour.find(params[:id])
    @hour.destroy

    respond_to do |format|
      format.html { redirect_to hours_url }
      format.json { head :ok }
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_filter :redirect_if_already_logged_in, :except => :destroy
  
  def index
  end

  def verify
    if params[:username] == ""
      usernameError = "Username field empty."
    end

    if params[:password] == ""
      passwordError = "Password field empty."
    end

    unless usernameError.nil? && passwordError.nil?
      flash.now[:passwordError] = passwordError
      flash.now[:usernameError] = usernameError 
      flash.now[:params] = params
      render "index"
      return
    end

    user = User.where(:name => params[:username], :password => params[:password]).first

    unless user.nil?
      session[:user_id] = user.id
      
      if user.role.admin?
        redirect_to admin_path
        return
      else
        redirect_to teacher_path
        return
      end
    else
      flash.now[:params] = params
      flash.now[:error] = "Login failed."
      render "index"
    end
  end

  def destroy
    if already_logged_in?    
      reset_session
    end
    redirect_to login_path
  end

  def already_logged_in?
    unless session[:user_id].nil?
      true  
    end
  end
  
  private
  def redirect_if_already_logged_in
    if already_logged_in?
      redirect_to admin_path
    end    
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_for_admin
  
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles } 
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end 

app/helpers/application_helper.rb
module ApplicationHelper
end 

app/helpers/course_types_helper.rb
module CourseTypesHelper
end 

app/helpers/courses_helper.rb
module CoursesHelper
end
 

app/helpers/hours_helper.rb
module HoursHelper
end
 

app/helpers/login_helper.rb
module LoginHelper
end
 

app/helpers/roles_helper.rb
module RolesHelper
end
 

app/helpers/teacher_helper.rb
module TeacherHelper
end
 

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end
 

app/helpers/users_helper.rb
module UsersHelper
end
 

app/helpers/wishes_helper.rb
module WishesHelper
end
 

app/views/hours/_form.html.erb
<%= form_for(@hour) do |f| %>
  <% if @hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
      <% @hour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hours %><br />
    <%= f.datetime_select :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 

app/views/hours/edit.html.erb
<h1>Editing hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @hour %> |
<%= link_to 'Back', hours_path %>
 

app/views/hours/index.html.erb
<h1>Listing hours</h1>

<table>
  <tr>
    <th>Hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hours.each do |hour| %>
  <tr>
    <td><%= hour.hours %></td>
    <td><%= link_to 'Show', hour %></td>
    <td><%= link_to 'Edit', edit_hour_path(hour) %></td>
    <td><%= link_to 'Destroy', hour, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hour', new_hour_path %>
 

app/views/hours/new.html.erb
<h1>New hour</h1>

<%= render 'form' %>

<%= link_to 'Back', hours_path %>
 

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hours:</b>
  <%= @hour.hours %>
</p>


<%= link_to 'Edit', edit_hour_path(@hour) %> |
<%= link_to 'Back', hours_path %>
 

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :permission %><br />
    <%= f.text_field :permission %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>
 

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Permission</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.permission %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>
 

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>
 

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Permission:</b>
  <%= @role.permission %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>
 