config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teaches, :dependent => :destroy
  has_many :users, :through => :teaches
end 

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :hours
  has_many :teaches, :through => :hours
end
 

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :teach
  belongs_to :course_type
  belongs_to :timesheet
end
 

app/models/role.rb
class Role < ActiveRecord::Base
  def admin?
    self.permission == "admin"
  end
end
 

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :user
  belongs_to :course, :dependent => :destroy
  has_many :hours, :dependent => :destroy
  has_many :wishes, :dependent => :destroy
end
 

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :hour
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # one-to-many association, the foreign key pointing to the Role table row is kept in this table
  # read for details: 
  # http://guides.rubyonrails.org/association_basics.html 
  # http://duanesbrain.blogspot.com/2006/05/ruby-on-rails-hasone-versus-belongsto.html
  belongs_to :role
  
  has_many :teaches, :dependent => :destroy
  has_many :courses, :through => :teaches
end 

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :teaches
  belongs_to :hour
end
 

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_for_admin
  
  def index
    redirect_to admin_timesheet_path
  end
  
end 

app/helpers/admin_helper.rb
module AdminHelper
end 

app/helpers/application_helper.rb
module ApplicationHelper
end 

app/helpers/course_types_helper.rb
module CourseTypesHelper
end 

app/helpers/courses_helper.rb
module CoursesHelper
end
 

app/helpers/hours_helper.rb
module HoursHelper
end
 

app/helpers/login_helper.rb
module LoginHelper
end
 

app/helpers/roles_helper.rb
module RolesHelper
end
 

app/helpers/teacher_helper.rb
module TeacherHelper
end
 

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end
 

app/helpers/users_helper.rb
module UsersHelper
end
 

app/helpers/wishes_helper.rb
module WishesHelper
end
 

app/views/admin/index.html.erb
<h1 style="text-align: center;"><%= t(:admin)%></h1> 

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta name="author" content="Szotyori Alpár" />
	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag 'application' %>
  	<%= csrf_meta_tags %>
	<title>Timetable</title>
</head>
<body>
	<div class="centered">
	
	<%= render :partial => "shared/header", :locals => {:user_id => session[:user_id], :user_name => @user_name, :admin => @admin } %>

	<table style="margin-left: auto; margin-right: auto; width:80%">
		<tr>
			<td class="errorCell">
				<%= params[:error] unless params[:error].nil? %>
			</td>
		</tr>
	</table>

<%= yield %>

	</div>
</body> 
</html>

app/views/shared/_header.html.erb
<table id="userBar">
<tr>
	<% if user_name.nil? %>
		<td style="text-align: right;"></td>
       	<td style="text-align: right; width: 120px;"><a href="<%= login_path %>"><%= t(:login) %></a></td>
    <% else 
    	if admin %>
		<td style="text-align: right;"><%= t(:welcome) %>, <b><%= user_name %></b> &nbsp;&nbsp;&nbsp;&nbsp;</td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_timesheet_path %>"><%= t(:timetable) %></a></td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_edit_timesheet_path %>"><%= t(:edit_timetable) %></a></td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_new_teacher_path %>"><%= t(:new_teacher) %></a></td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_show_edit_teacher_path %>"><%= t(:edit_teacher) %></a></td>
        <td style="text-align: center; width: 100px;"><a href="<%= logout_path %>"><%= t(:logout) %></a></td>	
    <% 	else %>
    	<td style="text-align: right;"><%= t(:welcome) %>, <b><%= user_name %></b> &nbsp;&nbsp;&nbsp;&nbsp;</td>
    	<td style="text-align: center; width: 120px;"><a href="<%= teacher_timesheet_path(user_id) %>"><%= t(:timetable) %></a></td>
    	<!-- <td style="text-align: center; width: 120px;"><a href="<%= "/teacher" %>"><%= t(:edit_wishes) %></a></td> -->
        <td style="text-align: center; width: 100px;"><a href="<%= logout_path %>"><%= t(:logout) %></a></td>	
   	<% 	end
   	 end %>
   	 <td style="text-align: right; width: 25px;">
   	 <%  if params[:locale] == "en" %>
			<a href="<%= request.path + "?locale=en"%>"><img src="/images/us.png" alt="EN" style="border: 0px;" width="19" height="14"/></a>
    <% else %>
    		<a href="<%= request.path + "?locale=en"%>"><img src="/images/us.png" alt="EN" style="border: 0px;"/></a>
	<% end %>
	</td>
	<td style="text-align: right; width: 25px;">
	<% if params[:locale] == "hu"%>      
			<a href="<%= request.path + "?locale=hu"%>"><img src="/images/hu.png" alt="HU" style="border: 0px" width="19" height="14"/></a>
	 <% else %>      
			<a href="<%= request.path + "?locale=hu"%>"><img src="/images/hu.png" alt="HU" style="border: 0px;"/></a>
	 <% end %>
	 </td>      
</tr>
</table> 