config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teaches, :dependent => :destroy
  has_many :users, :through => :teaches
end 

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :hours
  has_many :teaches, :through => :hours
end
 

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :teach
  belongs_to :course_type
  belongs_to :timesheet
end
 

app/models/role.rb
class Role < ActiveRecord::Base
  def admin?
    self.permission == "admin"
  end
end
 

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :user
  belongs_to :course, :dependent => :destroy
  has_many :hours, :dependent => :destroy
  has_many :wishes, :dependent => :destroy
end
 

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :hour
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # one-to-many association, the foreign key pointing to the Role table row is kept in this table
  # read for details: 
  # http://guides.rubyonrails.org/association_basics.html 
  # http://duanesbrain.blogspot.com/2006/05/ruby-on-rails-hasone-versus-belongsto.html
  belongs_to :role
  
  has_many :teaches, :dependent => :destroy
  has_many :courses, :through => :teaches
end 

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :teaches
  belongs_to :hour
end
 

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_for_admin
  
  def index
    redirect_to admin_timesheet_path
  end
  
end 

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_for_admin
  
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end 
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_filter :authenticate_for_admin
  
  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hours } 
    end
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
    @hour = Hour.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/new
  # GET /hours/new.json
  def new
    @hour = Hour.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/1/edit
  def edit
    @hour = Hour.find(params[:id])
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(params[:hour])

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render json: @hour, status: :created, location: @hour }
      else
        format.html { render action: "new" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hours/1
  # PUT /hours/1.json
  def update
    @hour = Hour.find(params[:id])

    respond_to do |format|
      if @hour.update_attributes(params[:hour])
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour = Hour.find(params[:id])
    @hour.destroy

    respond_to do |format|
      format.html { redirect_to hours_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end 

app/helpers/application_helper.rb
module ApplicationHelper
end 

app/helpers/course_types_helper.rb
module CourseTypesHelper
end 

app/helpers/courses_helper.rb
module CoursesHelper
end
 

app/helpers/hours_helper.rb
module HoursHelper
end
 

app/helpers/login_helper.rb
module LoginHelper
end
 

app/helpers/roles_helper.rb
module RolesHelper
end
 

app/helpers/teacher_helper.rb
module TeacherHelper
end
 

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end
 

app/helpers/users_helper.rb
module UsersHelper
end
 

app/helpers/wishes_helper.rb
module WishesHelper
end
 

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div> 
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :semester %><br />
    <%= f.number_field :semester %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>
 

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Title</th>
    <th>Description</th>
    <th>Semester</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.code %></td>
    <td><%= course.title %></td>
    <td><%= course.description %></td>
    <td><%= course.semester %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %> 
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>
 

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @course.code %>
</p>

<p>
  <b>Title:</b>
  <%= @course.title %>
</p>

<p>
  <b>Description:</b>
  <%= @course.description %>
</p>

<p>
  <b>Semester:</b>
  <%= @course.semester %>
</p> 


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>